version: smartide/v0.3
orchestrator:
  type: docker-compose
  version: 3
workspace:
  dev-container:
    service-name: smartide-template-python-vscode
    ports:
      tools-webide-port: 6800
      tools-ssh: 6822
      apps-application: 3001
    ide-type: vscode
    volumes: 
      git-config: true
      ssh-key: true
    command:
      - git submodule update --init --recursive
      - npm install --global http-server forever
    # - forever start $(which http-server) $(pwd) -a -p 3001 -c-1
      - http-server ./ -a -p 3001 -c-1
    # - forever list 查看所有 forever 运行的进程
    # - forever stop uid 停止运行指定 uid 的进程 forever stop 0
    # se start --host 1 git@github.com:limin-sites/as.git
      
  services:
    smartide-template-python-vscode:
      image: registry.cn-hangzhou.aliyuncs.com/smartide/smartide-python-v2-vscode:2198
      restart: always
      environment:
        ROOT_PASSWORD: root123
        LOCAL_USER_PASSWORD: root123
      volumes:
        - .:/home/project
      ports:
        - 6822:22
        - 6800:3000
        - 3001:3001
      networks:
        - smartide-network  
  networks:
    smartide-network:
      external: true
